const mongoose = require('mongoose');

// ---------------------------------------------------------------------------
// RiskSnapshot — daily risk score per hospital for the RiskHistory trend chart.
//
// Fields used by the frontend:
//   RiskHistory page → period label, risk score (line chart points)
//   Surveillance     → latest snapshot drives "completeness" progress
//   Admin Overview   → avg. completeness KPI
// ---------------------------------------------------------------------------

const riskSnapshotSchema = new mongoose.Schema({
  hospitalId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Hospital',
    required: true,
    index: true,
  },

  // The date this snapshot covers (one per calendar day per hospital)
  snapshotDate: { type: Date, required: true, index: true },

  // Model-computed overall risk score for this hospital on this date (0–100)
  riskScore: { type: Number, required: true, min: 0, max: 100 },

  // Breakdown of evidence factor scores (mirrors evidenceFactors in Alert)
  factors: {
    recentDiseaseActivity: { type: Number, default: 0, min: 0, max: 100 },
    hospitalAdmissions:    { type: Number, default: 0, min: 0, max: 100 },
    regionalActivity:      { type: Number, default: 0, min: 0, max: 100 },
    rainfall:              { type: Number, default: 0, min: 0, max: 100 },
    humidity:              { type: Number, default: 0, min: 0, max: 100 },
  },

  // Data completeness score on this day (used by Admin Overview KPI)
  completeness: { type: Number, default: 0, min: 0, max: 100 },

  // Whether this snapshot was generated by the model or manually overridden
  source: {
    type: String,
    enum: ['model', 'manual'],
    default: 'model',
  },
}, { timestamps: true });

// One snapshot per hospital per day
riskSnapshotSchema.index({ hospitalId: 1, snapshotDate: -1 }, { unique: true });

module.exports = mongoose.model('RiskSnapshot', riskSnapshotSchema);
